name: Jest Tests
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://postgres:password@localhost:5432/nextjs-panel-admin"
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Generate prisma client
        run: npm run generate:prisma
      - name: Test code
        run: npm run test:jest
