name: Test App
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
      = name: Generate prisma client
        run: npm run generate:prisma
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
